export const projects = [
  {
    title: 'Birla Carbon CV',
    description: "This project entails the development of a live streaming application tailored for the carbon business segment of ABG. This innovative app empowers users within carbon plants to actively observe and analyze various facets of their operations, including product quality, the condition of carbon containers or plants, and real-time monitoring of environmental factors such as temperature, moisture, and other pertinent details. This real-time insight equips users to proactively implement measures to preserve the quality of carbon during the production process.The implementation of websockets technology has been instrumental in achieving seamless and efficient live streaming capabilities, optimizing bandwidth usage particularly for multiple IP camera streams. Additionally, the project features the creation of dynamic analytical dashboards that provide users with comprehensive and relevant information for informed decision-making. This integrated solution enhances operational visibility and facilitates timely interventions, contributing to the overall efficiency and quality control of the carbon production process.",
    image: '/images/birla.png',
    tags: ["ReactJS", "TypeScript", "Websockets", "Material-UI", "Redux-Toolkit", "ChartJs", "Styled-Components"],
    source: 'https://github.com/vaibhavvarunkar/EnterpriseWebDesign',
    visit: 'https://tech-enterprise-website.netlify.app/',
    id: 3,
  },
  {
    title: 'MILE',
    description:"This project comprises a suite of analytical dashboards tailored for diverse business entities within the ABG Group, encompassing Ultratech, Grasim, Hindalco, and Fashion-Retail. Collaborating closely with senior developers, I contributed to the development of comprehensive, customizable dashboards designed to meet specific business requirements. These dashboards offer a holistic perspective on the overall health of the businesses, encompassing key metrics such as delivery estimates, profit and loss analysis, and operational efficiency.The successful implementation of this project is anticipated to yield substantial financial benefits, with an estimated annual savings of $60 million for the ABG Group. This outcome is attributed to the reduction of human errors and the integration of automation processes, thereby enhancing operational efficiency and optimizing resource utilization.",
    image: '/images/abg.png',
    tags: ["ReactJS", "TypeScript", "Material-UI", "Redux-Toolkit", "Recharts", "Styled-Components"],
    source: 'https://restaurantwebsitebyvaibhav.netlify.app/',
    visit: 'https://github.com/vaibhavvarunkar/restaurantWebsiteFlexbox',
    id: 1,
  },
  {
    title: 'Pallete Paws',
    description: "This project is an educational web application that I, as a dedicated developer, helped bring to life. LearnHub is designed to provide a dynamic and comprehensive learning experience, offering a diverse course catalog spanning various subjects and skill levels. With engaging multimedia content, expert instructors, and interactive learning paths, the platform ensures an effective and enjoyable learning journey. Community interaction, personalized recommendations, and certification upon completion enhance the user experience, while the platform's responsive design makes learning accessible across devices. As a developer, my commitment to continuous improvement ensures LearnHub remains at the forefront of online education, where knowledge seamlessly meets innovation..",
    image: '/images/AISS.jpg',
    tags: ["React", "Material UI", "Redux-Thunk", "TypeScript", "Styled Components"],
    source: 'https://gracious-bhabha-8eb005.netlify.app/',
    visit: 'https://github.com/vaibhavvarunkar/React-voice-assistant-news-app',
    id: 0,
  },
  {
    title: 'Bellboy',
    description: "This project involves the development of a sophisticated web application designed to streamline hotel operations by effectively managing both staff and customer interactions. The application serves as a centralized platform, integrating robust features to enhance overall efficiency and guest satisfaction. Key features include staff managemen, customer profiles, reservation system, check-in and check-out workflow, staff scheduling and communication, task management, billing. This web application is poised to revolutionize hotel management by optimizing internal processes, enhancing customer service, and providing valuable insights through data analytics. With an emphasis on user-friendly design and cutting-edge technology, this solution aims to elevate the overall guest experience and operational efficiency within the hospitality industry.",
    image: '/images/jwtss.jpg',
    tags: ["ReactJS", "TypeScript", "React-Query", "Material-UI", "Styled-Components", "Websockets"],
    source: 'https://jwt-app-vaibhav.herokuapp.com/',
    visit: 'https://github.com/vaibhavvarunkar/jwt-auth',
    id: 1,
  },
  {
    title: 'Qause',
    description: "This project involves the creation of a comprehensive website dedicated to connecting NGOs and volunteers. The platform serves as a centralized hub where non-profit organizations can post their initiatives and volunteer opportunities, while individuals seeking to contribute their time and skills can easily find and engage with meaningful causes. Through user-friendly features, such as customizable profiles for both NGOs and volunteers, the website aims to streamline the matching process, fostering efficient collaboration. Implemented with a responsive design, the site ensures accessibility across various devices, enhancing user experience. Robust search functionalities enable volunteers to discover opportunities aligned with their interests and skill sets, while NGOs can efficiently recruit individuals who resonate with their mission. The inclusion of a secure messaging system facilitates communication and coordination between NGOs and volunteers. This project embodies a commitment to social impact by leveraging technology to facilitate connections and amplify the efforts of NGOs and volunteers. The website not only promotes a culture of altruism but also contributes to the advancement of social causes by fostering collaboration and community engagement.",
    image: '/images/ebookss.jpg',
    tags: ["NextJS", "TypeScript", "React-Query", "Material-UI", "Styled-Components"],
    source: 'https://ebook-node-stripe-app.herokuapp.com/',
    visit: 'https://github.com/vaibhavvarunkar/NodeStripeEbookProject',
    id: 2,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey as an IT engineering student in Pune', },
  { year: 2019, text: "Started learning about developement processes and fundamentals. Started learning web developement from basics", },
  { year: 2020, text: 'Created my first ever project with HTML, CSS and JS. Then went on to building projects and learnt MERN stack also built couple of full-stack projects', },
  { year: 2021, text: 'Got an internship at Creatosaurus as a MERN stack developer also got a full-time job at webknot technologies in October', },
  { year: 2022, text: 'Completed my graduation with 8.85 CGPA and continued this beautiful journey', },
];