export const projects = [
  {
    title: 'AI Powered News App',
    description: "This is by far my most advance project till the date. In this web app I created a Voice assisted News App with the help of Alan AI studio. Users can search news by keywords like sports, technologies and much more.",
    image: '/images/AISS.jpg',
    tags: ["React", "Material UI", "Alan AI API"],
    source: 'https://github.com/vaibhavvarunkar/React-voice-assistant-news-app',
    visit: 'https://gracious-bhabha-8eb005.netlify.app/',
    id: 0,
  },
  {
    title: 'Jwt Authentication',
    description: "In this project I implemented authentication system using JWT tokens. I have also applied authentication to the some other API's of the website. The user passwords are also hashed for advance security.",
    image: '/images/jwtss.jpg',
    tags: ["Html", "Css", "Node", "MongoDB", "Express"],
    source: 'https://github.com/vaibhavvarunkar/jwt-auth',
    visit: 'https://jwt-app-vaibhav.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Online Ebook Selling Website',
    description: "In this project I created a web page where user can buy an ebook using cards. I have also implemented payment gateway using stripe API.",
    image: '/images/ebookss.jpg',
    tags: ["Html", "Css", "Node", "Express", "Stripe API"],
    source: 'https://github.com/vaibhavvarunkar/NodeStripeEbookProject',
    visit: 'https://ebook-node-stripe-app.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Tech Startup Website Design',
    description: "In this mini project I implemented a frontend design for a tech enterprise website. I have used some css animations here for better UX.",
    image: '/images/techs.jpg',
    tags: ["Html", "Css", "Js", "Jquery"],
    source: 'https://github.com/vaibhavvarunkar/EnterpriseWebDesign',
    visit: 'https://tech-enterprise-website.netlify.app/',
    id: 3,
  },
  {
    title: 'Tech Startup Website Design',
    description: "In this website I used Html and css flexbox to implement a fully responsive website design for a restaurant. ",
    image: '/images/restss.jpg',
    tags: ["Html", "Css", "Flexbox"],
    source: 'https://github.com/vaibhavvarunkar/restaurantWebsiteFlexbox',
    visit: 'https://restaurantwebsitebyvaibhav.netlify.app/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey as an engineering student', },
  { year: 2019, text: 'Started learning Web Developement', },
  { year: 2020, text: 'Created my first ever project', },
  { year: 2021, text: 'Got an internship at Creatosaurus as an full stack web developer', },
  { year: 2022, text: 'Will be completing my BE degree', },
];